#!/bin/bash

# initial reference:
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config window_border                off
#yabai -m config window_border_width          6
#yabai -m config active_window_border_color   0xffa35763
#yabai -m config normal_window_border_color   0xff353c54
#yabai -m config insert_feedback_color        0xaa7c5c9c

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 30
yabai -m config right_padding                40
yabai -m config window_gap                   10

# mission-control desktop labels
yabai -m space 1 --label mail
yabai -m space 2 --label comm
#yabai -m space 3 --label web
#yabai -m space 4 --label terminal
#yabai -m space 5 --label media

# specific space settings
#yabai -m config --space web  layout        float

# window rules
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Slack$" space=comm
yabai -m rule --add app="^Notes$" space=comm
#yabai -m rule --add app="^Safari$" space=web
#yabai -m rule --add app="^Firefox$" space=web
#yabai -m rule --add app="^Spotify$" space=media
#yabai -m rule --add app="^iTerm2$" space=terminal

# unmanaged apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Zoom$" manage=off

