--vim.o.airline_theme = 'onedark'
--vim.opt_global.airline_powerline_fonts = 1
--vim.opt_global.better_whitespace_enabled = 1
--vim.opt_global.colorscheme = 'onedark'
--vim.opt_global.mapleader = ','
--vim.opt_global.NERDTreeShowHidden = 1
vim.opt.autoindent = true
vim.opt.backspace = { 'indent', 'eol', 'start' }
vim.opt.backup = false
vim.opt.clipboard = 'unnamed'
vim.opt.colorcolumn = { '81', '121' }
vim.opt.compatible = false
vim.opt.completeopt = { 'menuone', 'noselect' }
vim.opt.cursorline = true
vim.opt.errorbells = false
vim.opt.expandtab = false
vim.opt.foldenable = true
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.modifiable = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 4
vim.opt.showmode = false
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.wrap = true
vim.opt.writebackup = false
