cask_args appdir: "~/Applications"

# Tap
tap 'caskroom/cask'
tap 'homebrew/cask-drivers'
tap 'khanhas/tap'

# Brew
brew 'stow'
brew 'vim'
brew 'python'
brew 'python3'
brew 'git'
brew 'wget'
brew 'zsh'
brew 'curl'
brew 'tree'
brew 'thefuck'
brew 'jq'
brew 'zsh-completions'
brew 'fzf'
brew 'packer'
# brew 'terraform' #commenting this out until I'm fully migrated to 0.12 syntax

# Cask
cask '1password'
cask 'slack'
cask 'iterm2'
cask 'docker'
cask 'spotify'
cask 'appcleaner'
cask 'caffeine'
cask 'virtualbox'
cask 'vagrant'
cask 'logitech-options'
cask 'firefox'

# Visual stuff
brew 'spicetify-cli'
