cask_args appdir: "~/Applications"

# Tap
tap 'caskroom/cask'
tap 'homebrew/cask-drivers'

# Brew
brew 'stow'
brew 'vim'
brew 'python'
brew 'python3'
brew 'git'
brew 'wget'
brew 'zsh'
brew 'curl'
brew 'tree'
brew 'thefuck'
brew 'jq'
brew 'zsh-completions'

# Cask
cask '1password'
cask 'slack'
cask 'iterm2'
cask 'docker'
cask 'spotify'
cask 'appcleaner'
cask 'caffeine'
cask 'virtualbox'
cask 'vagrant'
cask 'terraform'
cask 'packer'
cask 'logitech-options'
