cask_args appdir: "~/Applications"

# Tap
tap 'caskroom/cask'
tap 'homebrew/cask-drivers'
tap 'warrensbox/tap'
tap 'homebrew/cask-fonts'

# Brew
brew 'stow'
brew 'neovim'
brew 'python'
brew 'python3'
brew 'git'
brew 'wget'
brew 'zsh'
brew 'curl'
brew 'tree'
brew 'jq'
brew 'zsh-completions'
brew 'fzf'
brew 'tfswitch'
brew 'node'

# Cask
cask '1password'
cask 'slack'
cask 'iterm2'
cask 'docker'
cask 'spotify'
cask 'appcleaner'
cask 'caffeine'
cask 'virtualbox'
cask 'firefox'
cask 'font-firacode-nerd-font'
cask 'font-firamono-nerd-font'
