# Tap
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'hashicorp/tap'

# Brew
brew 'awscli'
brew 'azure-cli'
brew 'gh'
brew 'git'
brew 'glow'
brew 'go'
brew 'jq'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'nomad'
brew 'packer'
brew 'qmk/qmk/qmk'
brew 'ripgrep'
brew 'starship'
brew 'stow'
brew 'terraform-ls'
brew 'tmux'
brew 'tree'
brew 'vault'
brew 'vim'
brew 'warrensbox/tap/tfswitch'
brew 'zsh'
brew 'zsh-completions'

# Cask
cask 'alacritty'
cask 'caffeine'
cask 'firefox'
cask 'font-firacode-nerd-font'
cask 'font-firamono-nerd-font'
cask 'karabiner-elements'
cask 'logitech-options'
cask 'obsidian'
cask 'session-manager-plugin'
cask 'spotify'
cask 'vagrant'
cask 'virtualbox'

# Mac App Store
mas '1Password 7 - Password Manager', id: 1333542190
mas 'Slack', id: 803453959
