env:
  TERM: xterm-256color

window:
  decorations: none

font:
  normal:
    family: "Source Code Pro for Powerline"
    style: Regular

  bold:
    family: "Source Code Pro for Powerline"
    style: Bold

  italic:
    family: "Source Code Pro for Powerline"
    style: Italic

  bold_italic:
    family: "Source Code Pro for Powerline"
    style: Bold Italic

  size: 12

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

live_config_reload: true
