add_newline = false

# General prompt configuration

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[hostname]
format = "[$hostname]($style) in "

[memory_usage]
symbol = " "

# Languages and whatnot

[aws]
symbol = " "
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[terraform]
format = "[$symbol$workspace]($style) "
symbol = "tf "
style = "105"
disabled = true
